ZSH=$HOME/.oh-my-zsh
ZSH_THEME="proghat"

# upgrade_oh_my_zsh command updates oh-my-zsh
DISABLE_AUTO_UPDATE="true"
DISABLE_CORRECTION="true"
ALWAYS_LAST_PROMPT="true"

plugins=(git sublime)

source $ZSH/oh-my-zsh.sh

# Load custom environment variables
ENV_FILE=~/.env
if [ -f $ENV_FILE ]; then
  source $ENV_FILE
fi

# Customize to your needs...
export PATH=$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# Initialize rbenv
eval "$(rbenv init -)"
